fix: return 200 instead of 500 when a nested entry is submitted with an unknown id (#3891)
Fix https://errors.data.gouv.fr/organizations/sentry/issues/299180/ on
`PUT` https://demo.data.gouv.fr/api/1/datasets/67f988bf9ea6979ac6079373/

```
AttributeError: 'NoneType' object has no attribute 'to_mongo'
(15 additional frame(s) were not displayed)
...
  File "udata/forms/__init__.py", line 20, in process
    super(CommonFormMixin, self).process(
  File "wtforms/form.py", line 128, in process
    field.process(formdata, data, extra_filters=field_extra_filters)
  File "udata/forms/fields.py", line 551, in process
    super(NestedModelList, self).process(formdata, data, **kwargs)
  File "wtforms/fields/list.py", line 91, in process
    self._add_entry(formdata, obj_data, index=index)
  File "udata/forms/fields.py", line 603, in _add_entry
    initial = flatten_json(self.nested_form, data.to_mongo(), prefix)
```