fix: restrict Discussion.subject to models supporting discussions (#3884)
```
AttributeError: 'License' object has no attribute 'self_web_url'
(17 additional frame(s) were not displayed)
...
  File "flask_restx/marshalling.py", line 170, in __format_field
    value = field.output(key, data, ordered=ordered)
  File "flask_restx/fields.py", line 200, in output
    value = get_value(key if self.attribute is None else self.attribute, obj)
  File "flask_restx/fields.py", line 74, in get_value
    return key(obj)
  File "udata/core/discussions/api.py", line 80, in <lambda>
    attribute=lambda d: d.self_web_url(), description="The discussion web URL"
  File "udata/core/discussions/models.py", line 233, in self_web_url
    return self.subject.self_web_url(append="/discussions", discussion_id=self.id, **kwargs)
```

5 discussions exists in demo. Nothing in production.