fix: transfer api reference injection (#3930)
Fix https://errors.data.gouv.fr/organizations/sentry/issues/301567/ and
https://errors.data.gouv.fr/organizations/sentry/issues/301560

MultipleObjectsReturned api.transfers
2 or more items returned, instead of 1

AttributeError api.transfers
'License' object has no attribute 'organization'

Also fix https://errors.data.gouv.fr/organizations/sentry/issues/301890/
Error creating notification for admin user 6a9e59fb93ec631ffa38e226 and
recipient 6a9e59fb93ec631.. api.transfers