fix: return 404 instead of 500 when updating a non-member (#3888)
Fix
"[AttributeError](https://errors.data.gouv.fr/organizations/sentry/issues/298642/?referrer=alert_email&alert_type=email&alert_timestamp=1785368919601&alert_rule_id=10&notification_uuid=0a362c19-2e48-43ba-bd50-e57d8f5ef2ff&environment=demo.data.gouv.fr)
api.member 'NoneType' object has no attribute 'role'"

```
AttributeError: 'NoneType' object has no attribute 'role'
(4 additional frame(s) were not displayed)
...
  File "flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "flask_restx/resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
  File "udata/api/__init__.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "flask_restx/marshalling.py", line 246, in wrapper
    resp = f(*args, **kwargs)
  File "udata/core/organization/api.py", line 590, in put
    old_role = member.role
```