fix: do not send harvest connection errors to Sentry (#3543)
Prevent sending to Sentry errors `NameResolutionError`,
`ConnectTimeoutError` or `SSLError`:

```
NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f2b17d16490>: Failed to resolve 'numerique.brocaslesforges.fr' ([Errno -2] Name or service not known)
(1 additional frame(s) were not displayed)
```

or 

```
ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f2b17c88090>, 'Connection to data.naturefrance.fr timed out. (connect timeout=None)')
(1 additional frame(s) were not displayed)
...
  File "urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "urllib3/connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
  File "urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
```

or 

```
HTTPSConnectionPool(host='donnees.grandchambery.fr', port=443): Max retries exceeded with url: /api/explore/v2.1/catalog/exports/dcat/?where=keyword%3D%2220006911000019%22&include_exports=json%2Ccsv%2Cshp%2Cgeojson&lang=fr (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:992)')))
```

---------

Co-authored-by: maudetes <maudet.estelle@gmail.com>