fix: return 400 instead of 500 on malformed member assignments payload (#3887)
Fix
"[AttributeError](https://errors.data.gouv.fr/organizations/sentry/issues/298643/?referrer=alert_email&alert_type=email&alert_timestamp=1785369271816&alert_rule_id=10&notification_uuid=d878dc18-e063-4c49-95d2-a39296cef076&environment=demo.data.gouv.fr)
api.member_assignments 'str' object has no attribute 'get'"

```
AttributeError: 'str' object has no attribute 'get'
(5 additional frame(s) were not displayed)
...
  File "flask_restx/resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
  File "udata/api/__init__.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "flask_restx/marshalling.py", line 246, in wrapper
    resp = f(*args, **kwargs)
  File "udata/core/organization/api.py", line 646, in put
    desired_subjects = resolve_assignment_subjects(request.json or [], org)
  File "udata/core/organization/api.py", line 62, in resolve_assignment_subjects
    cls_name = raw.get("class")
```